author: Stongxin
name: Elenasong

title: Welcome to my blog
description: >- # this means to ignore newlines until "baseurl:"
 所以不用老去纠结每件事,集中精力完成眼前的事情的过程中,愿望自然就会实现了吧。

email: 1710530664@qq.com

# social links
twitter_username: Stongxin
github_username:  Stongxin
# rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# baseurl: http://127.0.0.1:4000
header_pages:
  - index.md
  - blog.md

# Config section the home


# Build settings
markdown: kramdown

jekyll-theme-experiment:
  about:
    avatar : https://robohash.org/experiment-avatar.png?size=300x300

  portfolio:
    title: 项目展示
    projects:

      - name: 测试项目demo1
        github: https://github.com/Stongxin
        img_relative_url: /assets/example.png

      - name: 测试项目demo2
        github: https://github.com/Stongxin
        img_relative_url: /assets/example.png

  tools:
    title: 一些工具
    icons:
      - relative_url: /assets/icons/bitbucket/bitbucket-original.svg
      - relative_url: /assets/icons/heroku/heroku-original.svg
      - relative_url: /assets/icons/git/git-original.svg
      - relative_url: /assets/icons/express/express-original.svg
      - relative_url: /assets/icons/angularjs/angularjs-original.svg

exclude:
  - Gemfile
  - Gemfile.lock
